sudo: required
addons:
  chrome: stable

services:
  - docker

language: python
python: '3.6'

cache:
  - pip

install:
  - pip install pipenv==8.3.2
  - pipenv install --dev --deploy
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker network create rasrmdockerdev_default

script:
  - pipenv check --style . --max-line-length 120
  - travis_wait 20 make test

branches:
  only:
    - master
