language: python
python: '3.6'

cache:
  - pip

install:
  - pip install pipenv==8.3.2
  - pipenv install --dev --deploy

script:
  - pipenv check --style . --max-line-length 120

branches:
  only:
    - master