sudo: required

services:
  - docker

language: python
python: '3.6'

env:
  global:
    - DOCKER_CACHE_FILE=$HOME/docker/cache.tar.gz

cache:
  pip: true
  directories:
    - $HOME/docker/

before_install:
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi

install:
  - pip install pipenv==8.3.2
  - pipenv install --dev --deploy
  - npm install -g phantomjs-prebuilt
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker network create rasrmdockerdev_default

script:
  - pipenv check --style . --max-line-length 120
  - make start_services
  - mkdir -p $(dirname ${DOCKER_CACHE_FILE}) && docker save $(docker images -qa) | gzip > ${DOCKER_CACHE_FILE}
  - make setup acceptance_tests stop_services

branches:
  only:
    - master
