import os


class Config(object):
    PROTOCOL = os.getenv('PROTOCOL', 'http')
    INFO = '/info'

    SECURE_MESSAGE_SERVICE_HOST = os.getenv('SECURE_MESSAGE_SERVICE_HOST', 'localhost')
    SECURE_MESSAGE_SERVICE_PORT = os.getenv('SECURE_MESSAGE_SERVICE_PORT', 5050)
    SECURE_MESSAGE_SERVICE = '{}://{}:{}'.format(PROTOCOL, SECURE_MESSAGE_SERVICE_HOST, SECURE_MESSAGE_SERVICE_PORT)

    FRONTSTAGE_SERVICE_HOST = os.getenv('FRONTSTAGE_SERVICE_HOST', 'localhost')
    FRONTSTAGE_SERVICE_PORT = os.getenv('FRONTSTAGE_SERVICE_PORT', 8080)
    FRONTSTAGE_SERVICE = '{}://{}:{}'.format(PROTOCOL, FRONTSTAGE_SERVICE_HOST, FRONTSTAGE_SERVICE_PORT)

    BACKSTAGE_SERVICE_HOST = os.getenv('BACKSTAGE_SERVICE_HOST', 'localhost')
    BACKSTAGE_SERVICE_PORT = os.getenv('BACKSTAGE_SERVICE_PORT', 5001)
    BACKSTAGE_SERVICE = '{}://{}:{}'.format(PROTOCOL, BACKSTAGE_SERVICE_HOST, BACKSTAGE_SERVICE_PORT)

    PARTY_SERVICE_HOST = os.getenv('PARTY_SERVICE_HOST', 'localhost')
    PARTY_SERVICE_PORT = os.getenv('PARTY_SERVICE_PORT', 8081)
    PARTY_SERVICE = '{}://{}:{}'.format(PROTOCOL, PARTY_SERVICE_HOST, PARTY_SERVICE_PORT)

    COLLECTION_INSTRUMENT_SERVICE_HOST = os.getenv('COLLECTION_INSTRUMENT_SERVICE_HOST', 'localhost')
    COLLECTION_INSTRUMENT_SERVICE_PORT = os.getenv('COLLECTION_INSTRUMENT_SERVICE_PORT', 8082)
    COLLECTION_INSTRUMENT_SERVICE = '{}://{}:{}'.format(PROTOCOL, COLLECTION_INSTRUMENT_SERVICE_HOST, COLLECTION_INSTRUMENT_SERVICE_PORT)

    DJANGO_SERVICE_HOST = os.getenv('DJANGO_SERVICE_HOST', 'localhost')
    DJANGO_SERVICE_PORT = os.getenv('DJANGO_SERVICE_PORT', 8040)
    DJANGO_SERVICE = '{}://{}:{}'.format(PROTOCOL, DJANGO_SERVICE_HOST, DJANGO_SERVICE_PORT)

    FRONTSTAGE_API_SERVICE_HOST = os.getenv('FRONTSTAGE_API_SERVICE_HOST', 'localhost')
    FRONTSTAGE_API_SERVICE_PORT = os.getenv('FRONTSTAGE_API_SERVICE_PORT', 8083)
    FRONTSTAGE_API_SERVICE = '{}://{}:{}'.format(PROTOCOL, FRONTSTAGE_API_SERVICE_HOST, FRONTSTAGE_API_SERVICE_PORT)
