version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install dependencies
          command: |
            pip install --user pipenv==8.3.2
            export PATH=$HOME/.local/bin:$PATH
            pipenv install --dev --deploy

      - run:
          name: Start container and verify it's working
          command: |
            export PATH=$HOME/.local/bin:$PATH
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
            docker network create rasrmdockerdev_default
            make start_services || cd tmp_ras_rm_docker_dev && docker-compose -f dev.yml -f ras-services.yml -f rm-services.yml logs

      - run:
          name: Run system tests
          command: |
            make system_tests