version: 2
jobs:
  build:
    machine:
        docker_layer_caching: true
      
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
            export PATH="~/.pyenv/bin:$PATH"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            pyenv install 3.6.0
            pip install --user pipenv==8.3.2
            export PATH=$HOME/.local/bin:$PATH
            pipenv install --dev --deploy

      - run:
          name: Start container and verify it's working
          command: |
            export PATH=$HOME/.local/bin:$PATH
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
            docker network create rasrmdockerdev_default
            make start_services wait_for_services || docker-compose -f dev.yml -f ras-services.yml -f rm-services.yml logs
      - run:
          name: Install Chrome
          command: |
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb

      - run:
          name: Run system tests
          command: |
            export PATH=$HOME/.local/bin:$PATH
            make system_tests setup acceptance_tests stop_services