version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install dependencies
          command: |
            pip install --user pipenv==8.3.2
            pipenv install --dev --deploy

      - run:
          name: Start container and verify it's working
          command: |        
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
            docker network create rasrmdockerdev_default
            make start_services

      - run:
          name: Run system tests
          command: |
            make system_tests